config/routes.rb
Rails.application.routes.draw do

  get 'transition/show'
  devise_for :companies
  get 'public/index'
  get 'public/private'

  devise_for :users, controllers: { registrations: "registrations"} do
    member do
      get :following, :followers
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
    resources :posts
    resources :comments
    resources :interests
  end

  root to: "posts#index"

  resources :posts do
    member do
      put "like" => "posts#vote"
    end
    resources :users
    resources :interests
    post 'comments', to: 'comments#create'

  end

  resources :comments do
    resources :users
  end

  resources :users do
    resources :posts
    resources :interests
  end
  resources :interests do
    resources :posts
    resources :users
  end
  resources :relationships, only: [:create, :destroy] do
    resources :users
  end
  get 'users/:id/user_posts' => 'users#user_posts', :as => :users_posts
  get 'users/:id/current_user_posts' => 'users#current_user_posts', :as => :current_user_posts
  get 'interests/:id/post_by_interest' => 'interests#post_by_interest', :as => :posts_by_interest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business_model.rb
class BusinessModel < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/interest.rb
class Interest < ApplicationRecord
    has_many :users
    has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :interest
  has_many :comments, dependent: :destroy
  has_one_attached :image


  scope :most_recent, -> { order(created_at: :desc) }
  def self.user_interesting
    self.find_by_sql(["SELECT * FROM posts"])
    # Post.find_by_sql(["SELECT title FROM posts WHERE author = ? AND created > ?", author_id, start_date])
  end
 
  # scope :tagging, -> { where(interest_id: Post.all.find_by(interest_id: @user).content) }
 
  # Ex:- scope :active, -> {where(:active => true)}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"

    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_voter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_one_attached :avatar
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  belongs_to :interest
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships
 
  validates :email, :uniqueness => true
  validates :username, :uniqueness => true

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end

  def self.search(search)
    if search
      where(["username LIKE ?","%#{search}%"])
    else
      all
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    include CommentsHelper
    before_action :authenticate_user!
    
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.new(comment_params)
        @comment.user = current_user
        if @comment.save
            redirect_to post_path(@post)
        else
            render 'new'
        end
        # @comment = @post.comment.new(comment_params)
        # @user = current_user
        # if @comment.save
        #     redirect_to post_path(post)
        #     flash[:notice] = 'Comments added'
        # else
        #     flash[:alert] = 'Failed'
        #     render :new
        # end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    include PostsHelper
    include UsersHelper
    # before_action :set_user, only: %i[show]
    before_action :set_post, only: %i[show edit update edit destroy vote]
    before_action :authenticate_user!
    before_action :current_user, only: %i[index upvote new create]

    def index
        @posts = Post.all.most_recent
        @user_interest = current_user.interest
        @user_following = current_user.following
    end

    def show
        @comment = Comment.new
        @post_user = @post.user
        @comments = @post.comments
    end

    def new
        @post = current_user.posts.build
    end

    def create
        @post = current_user.posts.build(post_params)

        if @post.save
            redirect_to posts_path
            flash[:notice] = 'Posted'
        else
            flash[:alert] = 'Failed'
            redirect_to posts_path
        end
    end

    def edit; end

    def update
        @post.update(post_params)
        redirect_to posts_path
    end

    def destroy
        Post.find(params[:id]).destroy
        redirect_to posts_path
    end

    def vote
      @post.upvote_by current_user
      redirect_back fallback_location: root_path
    end
    
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  include PostsHelper
  include UsersHelper
  # before_action :set_user, only: %i[index]


  def index; end

  def private; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include UsersHelper
    before_action :set_user, only: %i[show user_posts]
    before_action :authenticate_user!
    def index
        @users = User.search(params[:search])
        # @users = User.all
    end

    def show; end

    def user_posts
        @posts = @user.posts
    end

    def current_user_posts
        @current_posts = current_user.posts
    end

    def edit
        @user_name = User.find(1)
    end
    
    def following
        @title = "Following"
        @user = User.find(params[:id])
        render 'following'
    end

    def followers
        @title = "Followers"
        @user = User.find(params[:id])
        render 'followers'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def user_avatar(user, size=40)
        if user.avatar.attached?
            user.avatar.variant(resize: "#{size}x#{size}")
        else
            gravatar_image_url(user.username, size: size)
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
    def comment_params
        params.require(:comment).permit(:text, :user_id, :post_id)
    end

    private

    def set_comment
        @comment = Comment.find(params[:id])
    end
end

app/helpers/interests_helper.rb
module InterestsHelper
    def interest_params
        params.require(:interest).permit(:field_of_interest, :post_id)
    end

    private

    def set_interest
        @interest = Interest.find(params[:id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def post_params
        params.require(:post).permit(:content, :user_id,:image,:interest_id,  :tag_list, :comment_id,:created_at)
    end

    private

    def set_post
        @post = Post.find(params[:id])
    end

    
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/transition_helper.rb
module TransitionHelper
 
end

app/helpers/users_helper.rb
module UsersHelper
    def user_params
        params.require(:user).permit(:email, :username, :avatar, :interest_id)
    end

    private

    def set_user
        @user = User.find(params[:id])
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Businect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
      <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application','data-turbolinks-track': 'reload' %>
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link rel="stylesheet" href="https://cdn.rawgit.com/balzss/luxbar/ae5835e2/build/luxbar.min.css">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
      <link href="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v1.2.1/dist/jBox.all.min.css" rel="stylesheet">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>

  <div class="container">
    <div class="row">
      <div class="center-align">
        <p class="notice "><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
  </div>
  </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
        <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Full-stack web developer</h5>
                <p class="grey-text text-lighten-4">Connect with me if you want to create smart web application.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="https://github.com/muhenge/">GitHub</a></li>
                  <li><a class="grey-text text-lighten-3" href="https://www.linkedin.com/in/mugunga-herve-a62a0ab9/">LinkedIn</a></li>

                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2020 Copyright Ngenzi Herve            
            </div>
          </div>
        </footer>
            

app/views/shared/_nav.html.erb
 <header id="luxbar" class="luxbar-fixed">
    <input type="checkbox" class="luxbar-checkbox" id="luxbar-checkbox"/>
    <div class="luxbar-menu luxbar-menu-right luxbar-menu-light">
        <ul class="luxbar-navigation">
            <li class="luxbar-header">
                <%= link_to  "ISHEMA", posts_path, class:"luxbar-brand" %>
                <label class="luxbar-hamburger luxbar-hamburger-doublespin" 
                id="luxbar-hamburger" for="luxbar-checkbox"> <span></span> </label>
            </li>
            <% if user_signed_in? %>
                <li class="profile-nav">
                        <%= link_to  user_path(current_user), :action => 'go' do %>
                            <%= image_tag user_avatar(current_user, 55), class:"circle responsive-img", :title => "Visit #{current_user.username.capitalize} profile",alt: "user image" %>
                        <%end%>

                </li>
                <li class="luxbar-item">
                    <%= link_to "Home", posts_path %>
                </li>

                  <li class="luxbar-item">
                    <%= link_to "Find people", users_path %>
                </li>
                
                 <li class="luxbar-item">
                    <%= link_to "Edit my profile", edit_user_registration_path %>
                </li>
              
                <li class="luxbar-item">
                    <%= link_to "Manage my posts", current_user_posts_path(current_user) %>
                </li>

                <li class="luxbar-item">
                    <%= link_to "Logout", destroy_user_session_path, method: :delete%>
                </li>
                <%else%>
                <li class="luxbar-item">
                    <%= link_to  "Login", new_user_session_path %>
                </li>
            <%end%>
        </ul>
    </div>
</header>
 

app/views/shared/_relation.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>