config/routes.rb
Rails.application.routes.draw do

  get 'transition/show'
  devise_for :companies
  get 'public/index'
  get 'public/private'

  devise_for :users, controllers: { registrations: "registrations"} do
    member do
      get :following, :followers
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
    resources :posts
    resources :comments
    resources :interests
  end

  root to: "posts#index"

  resources :posts do
    member do
      put "like" => "posts#vote"
    end
    resources :users
    resources :interests
    post 'comments', to: 'comments#create'

  end

  resources :comments do
    resources :users
  end

  resources :users do
    resources :posts
    resources :interests
  end
  resources :interests do
    resources :posts
    resources :users
  end
  resources :relationships, only: [:create, :destroy] do
    resources :users
  end
  get 'users/:id/user_posts' => 'users#user_posts', :as => :users_posts
  get 'users/:id/current_user_posts' => 'users#current_user_posts', :as => :current_user_posts
  get 'interests/:id/post_by_interest' => 'interests#post_by_interest', :as => :posts_by_interest
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :interest
  has_many :comments, dependent: :destroy
  has_one_attached :image


  scope :most_recent, -> { order(created_at: :desc) }
  def self.user_interesting
    self.find_by_sql(["SELECT * FROM posts"])
    # Post.find_by_sql(["SELECT title FROM posts WHERE author = ? AND created > ?", author_id, start_date])
  end
 
  # scope :tagging, -> { where(interest_id: Post.all.find_by(interest_id: @user).content) }
 
  # Ex:- scope :active, -> {where(:active => true)}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    include PostsHelper
    include UsersHelper
    # before_action :set_user, only: %i[show]
    before_action :set_post, only: %i[show edit update edit destroy vote]
    before_action :authenticate_user!
    before_action :current_user, only: %i[index upvote new create]

    def index
        @posts = Post.all.most_recent
        @user_interest = current_user.interest
        @user_following = current_user.following
    end

    def show
        @comment = Comment.new
        @post_user = @post.user
        @comments = @post.comments
    end

    def new
        @post = current_user.posts.build
    end

    def create
        @post = current_user.posts.build(post_params)

        if @post.save
            redirect_to posts_path
            flash[:notice] = 'Posted'
        else
            flash[:alert] = 'Failed'
            redirect_to posts_path
        end
    end

    def edit; end

    def update
        @post.update(post_params)
        redirect_to posts_path
    end

    def destroy
        Post.find(params[:id]).destroy
        redirect_to posts_path
    end

    def vote
      @post.upvote_by current_user
      redirect_back fallback_location: root_path
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
    def post_params
        params.require(:post).permit(:content, :user_id,:image,:interest_id,  :tag_list, :comment_id,:created_at)
    end

    private

    def set_post
        @post = Post.find(params[:id])
    end

    
end

app/views/posts/edit.html.erb
<%= render partial: 'shared/nav' %>

<div class="container w-content">
    <div class="row">
        <%= form_for @post do |f| %>
            <%= f.text_area :content, placeholder: "Post here" %>
            <%= f.submit "Edit a post", class:"btn" %>
        <% end %>
        <%= link_to  "Back to posts", posts_path %>
    </div>
</div>

app/views/posts/index.html.erb
<%= render partial: 'shared/nav' %>



<div class="container">
        <div class="hide-on-large-only side-top">
                <%= render 'shared/relation' %><br><br>
                <%= link_to  "New Post", new_post_path %><br><br><br>
                <%= link_to "Posts based on #{@user_interest.field_of_interest}", posts_by_interest_path(@user_interest) %>
        </div>
 
    <div class="row w-content">
        <div class="col s12 m12 l8 post-container box-a">

            <% @posts.each do |post| %>
                <div class="post">
                <%= link_to post_path(post), :action => 'go' do %>
                <%= image_tag(post.image, :class => "user-img responsive-img", alt: "user image") if post.image.attached?%><br>
                    <p><%= simple_format(post.content.truncate(200)) %></p><br>
                <%end%>

                    <div class="row post-widgets">
                        <div class="col s6 l6 m6">
                            Posted by: <strong><%= link_to post.user.username.capitalize, post_user_path(post, post.user)%></strong><br>
                            <%= link_to like_post_path(post), method: :put do%>
                                <span class="medium material-icons">thumb_up</span>
                                <%= post.get_upvotes.size %><br>
                        <% end %>
                        </div>
                        <div class="col s6 l6 m6 box-b">
                        <%= post.created_at %>
                        </div>
                    </div>
                    <div>
                    </div>Tag to: <%= post.interest.field_of_interest %></div>
                
            <%end%>
        </div>
        <div class="col s12 m12 l4 sidebar hide-on-med-and-down">
        <%= form_for Post.new, :url => posts_path(), :method => :post do |f| %>
         <%= f.text_area :content, placeholder: "Post here" %>
         <div class="fileUpload">
                    
        <span class="tooltip" title="Add a picture for your post"> <i class="small material-icons">add_a_photo</i></span>
            <%= f.file_field :image,direct_upload: true, accept:'application/jpeg,application/jpg,application/png,application/gif',class:"upload tooltip", title:"Add a picture for your post"%>
         </div>
         <%= f.label :field_of_interest, "Tag to" %>
         <%= f.collection_select(:interest_id, Interest.all, :id, :field_of_interest, :prompt => 'Tag to') %><br>
         <%= f.submit "Post",class:"btn post-btn" %>
        <% end %><br><br>
            <%= render 'shared/relation' %><br><br>
            <%= link_to "Posts based on #{@user_interest.field_of_interest}", posts_by_interest_path(@user_interest) %>
        </div>
    </div>

</div>

app/views/posts/new.html.erb
<%= render partial:'shared/nav' %>
<div class="container w-content">
   <div class="row">
      <%= link_to  "Back to posts", posts_path %><br>
      <%= form_for @post do |f| %>
        <%= f.text_area :content, placeholder: "Post here" %>
         <div class="fileUpload">
                    
            <span class=""> <i class="small material-icons">add_a_photo</i></span>
            <%= f.file_field :image,direct_upload: true, accept:'application/jpeg,application/jpg,application/png,application/gif',class:"upload tooltip", title:"Add a picture for your post"%>
         </div>
         <%= f.label :field_of_interest, "Tag to" %>
         <%= f.collection_select(:interest_id, Interest.all, :id, :field_of_interest, :prompt => 'Tag to') %><br>
         <%= f.submit "Post",class:"btn post-btn" %>
      <% end %>
   </div>
</div>

app/views/posts/show.html.erb
<%= render partial: 'shared/nav' %>
    <div class="row posted">
        <div class="col s12 m12 l8">
        <div class="post">
            
            <p class="flow-text"><%= simple_format(@post.content) %></p>
            <%= link_to like_post_path(@post), method: :put do %>
            <span class="medium material-icons">thumb_up</span>
                <%= @post.get_upvotes.size %>
            <% end %>
            <div class="comment-title blue-text">
                <h6>Comments</h6>
            </div>
                <% @comments.each do |comment| %>
                    <div class="comments">
                        <p class="comment-paragraph"><%= comment.text %><br></p>
                        <strong>At</strong>: <%= comment.created_at.strftime("%H:%M-%Z") %><br>
                        <strong>By</strong>: <%= link_to comment.user.username.capitalize, comment_user_path(comment, comment.user) %>
                    </div>
                    <% end %>
        </div>
        </div>
        <div class="col s12 m12 l4 fixing">
            <div class="user-on-comments">
             From: <%= link_to @post_user.username.capitalize , post_user_path(@post, @post.user) %>
             <%= render 'shared/relation' %>
            </div>
            <div class="input-comments">
                <%= form_with model: [@post, @comment], local: true do |f| %>
                    <%= f.text_area :text,rows: 15 %>
                    <%= f.submit "Add a comment", class:"btn" %>
                <% end %>
                 <div class="back">
                    <%= link_to  "Back to posts", posts_path %>
                </div>
            </div>
        </div>
           
    </div>